# https://docs.docker.com/compose/compose-file/

services:

  static:
    build:
      context: .
      dockerfile: dev/Dockerfile
    ports:
      - "8080:80"
    restart: on-failure
    volumes:
      # Mount site configuration directory
      - ./dev/usr-local-apache2-conf-config:/usr/local/apache2/conf/config:ro
      # Mount website directory
      - ./docs:/usr/local/apache2/htdocs:ro
